### ISSUE TITLE
Test new importer for Shapefiles, GPKG, GeoJSON and KML files

### ISSUE THREAD

**Issue by marthamareal** [geosolutions-it/geonode#1446]
## Expected Behavior
All formats should be imported successfully. 

**Note** Geoserver (is at 2.20.6)

## Specifications

  - GeoNode version: master.demo
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal news on this?

**Comment by marthamareal** [comment]
Not yet @giohappy. I will be testing it soon and let you know.

**Comment by marthamareal** [comment]
After testing this issue, below are my findings:
- I am unable to upload the GEOJSON files. (.json and .geojson)
- The form does not select multiple files with the same name but different extensions. eg (result.kml, result.json)
- Sometimes the upload starts and it never ends for a user to view the dataset
- Error is thrown on gpkg file i downloaded(no changes made to the downloaded file)
- 

NOTE: I downloaded all the formats from this dataset: https://master.demo.geonode.org/catalogue/#/dataset/3133

**Comment by mattiagiupponi** [comment]
Hi @marthamareal 

> * I am unable to upload the GEOJSON files. (.json and .geojson)
This looks like an issue with the FE. if the file is saved as geojson instead of json, the upload workflow works as expected.
The issue is that in the request the base_file is sent as "undefined"

> * The form does not select multiple files with the same name but different extensions. eg (result.kml, result.json)
This is an issue with the FE which does not permit it, maybe @DavidQuartz can help with this

> * Sometimes the upload starts and it never ends for a user to view the dataset
Do you have an example? 

> * Error is thrown on gpkg file i downloaded(no changes made to the downloaded file)
This error is thrown by the validation available in the GPKG handler. In detail "The geometry_type_name from the gpkg_geometry_columns table must be one of POINT, LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, or MULTIPOLYGON." this means that in the GPKG the geometry column is set as GEOMETRY instead of the real one. This is an issue on the gpkg export in geoserver I guess

**Comment by marthamareal** [comment]
@mattiagiupponi here are examples of never ending upload on master.demo `exec_id: "daa51977-2772-4e9b-880b-5b952095526a"`  `exec_id: "2be7eb36-1e0e-4b53-9d6d-8f813b1fb20e"`

**Comment by mattiagiupponi** [comment]
The case looks interesting.
Actually, the execution_id is still considered in running, but if we call manually the orchestrator, it evaluates the execution as "finished". Needs to go deeper in this.

```bash
ExecutionRequest.objects.filter(exec_id='daa51977-2772-4e9b-880b-5b952095526a')
-> <QuerySet [<ExecutionRequest: ExecutionRequest object (daa51977-2772-4e9b-880b-5b952095526a)>]>

x = ExecutionRequest.objects.filter(exec_id='daa51977-2772-4e9b-880b-5b952095526a').first()
x.status
-> 'running'

orchestrator.evaluate_execution_progress('daa51977-2772-4e9b-880b-5b952095526a')
x = ExecutionRequest.objects.filter(exec_id='daa51977-2772-4e9b-880b-5b952095526a').first()
x.status
-> 'finished'
```
 The only reason is that a celery task Result was not yet saved in the DB when the execution was in the evaluation status.

**Comment by mattiagiupponi** [comment]
Analysis for the exec_id: `2be7eb36-1e0e-4b53-9d6d-8f813b1fb20e`

Followings the celery tasks that return the exec_id in the params used for the evaluation
```python
[
    ('8554e0a0-ea42-4385-9773-3d9f057ccdf3', 2022-11-14 13:13:34:344918, 2022-11-14:13:13:34:810676, 'SUCCESS'),
    ('05fb7af5-1f9b-4b4c-a241-5d854ccd867f', 2022-11-14 13:13:34:826908, 2022-11-14:13:13:35:751269, 'SUCCESS'),
    ('4e8bc2a1-5e76-4c7e-9305-f5282c2455f4', 2022-11-14 13:13:34:827694, 2022-11-14:13:13:34:947597, 'SUCCESS'),
    ('25dc35e6-c338-42b7-bfcb-bf8fe2cbbb2c', 2022-11-14 13:13:36:606961, 2022-11-14:13:13:37:498157, 'SUCCESS'),
    ('96710406-f36d-4cb5-90a4-ff9916f9fdda', 2022-11-14 13:13:38:33856, 2022-11-14:13:13:47:17657, 'SUCCESS')
]
```
By running a new exec, looks like that the kwags are empty, while they should contain the number of dataset available:
```
In [1]: from importer.models import ResourceHandlerInfo

In [2]: ResourceHandlerInfo.objects.filter(execution_request='97206767-ac29-450e-adb3-bf6005de7bb7').first()
Out[2]: <ResourceHandlerInfo: ResourceHandlerInfo object (306)>

In [3]: ResourceHandlerInfo.objects.filter(execution_request='97206767-ac29-450e-adb3-bf6005de7bb7').first().kwargs
Out[3]: {'kwargs': {}}
```

Going to analyze the importer behaviour more closer, it may be a regression of this: https://github.com/geosolutions-it/geonode-importer/pull/142 which is now replacing in some way the kwargs

**Comment by mattiagiupponi** [comment]
The issue is not due a regression of that. In fact the evaluation stop it before the creation analysis of the layer imported:

Follows the celery timing 
'task_id', 'date_created', 'date_done', 'status'
```python
[('02adf2ef-43c2-4ac9-900e-be511b0851ce',
  datetime.datetime(2022, 11, 15, 14, 28, 45, 193021, tzinfo=<UTC>),
  datetime.datetime(2022, 11, 15, 14, 28, 45, 728137, tzinfo=<UTC>),
  'SUCCESS'),
 ('bb5a1ada-a014-461a-a853-dafa3067c9b5',
  datetime.datetime(2022, 11, 15, 14, 28, 45, 745606, tzinfo=<UTC>),
  datetime.datetime(2022, 11, 15, 14, 28, 45, 786126, tzinfo=<UTC>),
  'SUCCESS'),
 ('bcee9c94-1da9-4745-9350-e9f31c76d035',
  datetime.datetime(2022, 11, 15, 14, 28, 45, 746397, tzinfo=<UTC>),
  datetime.datetime(2022, 11, 15, 14, 28, 46, 277764, tzinfo=<UTC>),
  'SUCCESS'),
 ('bad34de0-62ba-4188-9197-09f65ee8aa96',
  datetime.datetime(2022, 11, 15, 14, 28, 46, 986336, tzinfo=<UTC>),
  datetime.datetime(2022, 11, 15, 14, 28, 47, 452153, tzinfo=<UTC>),
  'SUCCESS'),
 ('0607ef7a-3b9b-4b6e-b628-ac73b40d4bd0',
  datetime.datetime(2022, 11, 15, 14, 28, 47, 959371, tzinfo=<UTC>),
  datetime.datetime(2022, 11, 15, 14, 29, 1, 183326, tzinfo=<UTC>),
  'SUCCESS')]
```
This is the celery log:
```
[2022-11-15 14:29:01,264: INFO/ForkPoolWorker-2933] Execution progress with id a9a8480e-3433-4753-98c8-8014efacf53a is not finished yet, continuing
```

The timing looks good, we can evaluate to check also the total layers during this phase to avoid this issues

**Comment by giohappy** [comment]
Please @marthamareal test again all the formats and confirm that the issue you reported has been solved.

@mattiagiupponi I've tried to configure this example as a vector time series, through the metadata settings, but apparently the two fields are not imported as datetime fields, so Geoserver cannot enable the time dimension.

![image](https://user-images.githubusercontent.com/571129/213127440-485335f9-a07e-4615-b86f-905180c599e4.png)

I guess it's because ogr2ogr / PG do not perform any parsing and conversion on their own. 
How is this supposed to work? Will it only work for Shapefiles, where a field can be explicitly set as date? What about the other formats?

**Comment by mattiagiupponi** [comment]
Hi @giohappy 
As shown below, ogr2ogr return as "string" the type returned by the API
![image](https://user-images.githubusercontent.com/51856725/213144508-18feb535-3eb4-4f31-b28d-2abd55fb20e1.png)

Here we can evaluate to create a kind of analysis of the column and try to guess the type.
Here comes again the initial idea to have a pre-configuration panel where the user can select/choose the column and their type (the main reason why we still have the CSV in the old import way)

**Comment by marthamareal** [comment]
- From testing this issue on master.demo, I am able to upload Shapefiles, Geojson and KML files suceessfully.
- For the GPKG files, i still see the error below
![ll](https://user-images.githubusercontent.com/20810749/216554152-77cd1eb1-11f4-41df-9c77-5888b51c5916.png)

**Comment by mattiagiupponi** [comment]
Hi @marthamareal 
This is the same issue that was already described above and this is the reason:

This error is thrown by the validation available in the GPKG handler. In detail `The geometry_type_name from the gpkg_geometry_columns table must be one of POINT, LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, or MULTIPOLYGON.` this means that in the GPKG the geometry column is set as `GEOMETRY` instead of the real one.
Also the geometry column type of the table is saved as "GEOMETRY" instead of the correct one.
![image](https://user-images.githubusercontent.com/51856725/201892374-3612009d-e896-4eef-b6bf-78cd6c9353aa.png)
Follow an example of a correct and valid gpkg
![image](https://user-images.githubusercontent.com/51856725/201892687-7258e003-5c98-4223-babd-10342d23e0c5.png)

Where did you find this gpkg file? can you please pass me it so I can see if I can fix it?

**Comment by marthamareal** [comment]
[result.zip](https://github.com/geosolutions-it/geonode/files/10577350/result.zip)
